# %%
"""crystal_thermo.py

Utilities to model crystal thermo-optic and QPM/phase-matching quantities.

This module is meant to be *called* by the cavity + OPO model:
- your cavity code provides geometry/mode parameters (e.g. waist w0 in the crystal)
- this module provides temperature-dependent material/QPM factors

Conventions (keep consistent across the repo):
- SI units everywhere unless explicitly stated
- Wavelengths are in meters (m)
- Temperature is in Kelvin (K)
- Wave-vectors are in rad/m

The functions below are intentionally "base" building blocks.
You can later add crystal-specific coefficient sets (e.g. PPKTP) and polarization handling.
"""

from __future__ import annotations

# %%
from dataclasses import dataclass
import json
from pathlib import Path
from typing import Callable, Optional, Any

import numpy as np


# %%
# -----------------------------
# Helpers / small utilities
# -----------------------------

def sinc(x: np.ndarray | float) -> np.ndarray | float:
    """Normalized sinc: sin(x)/x with safe handling of x=0.

    Note: NumPy's np.sinc is sin(pi x)/(pi x), i.e. a different convention.
    """
    x_arr = np.asarray(x)
    out = np.ones_like(x_arr, dtype=float)
    mask = np.abs(x_arr) > 0
    out[mask] = np.sin(x_arr[mask]) / x_arr[mask]
    return out if isinstance(x, np.ndarray) else float(out)


def central_diff(f: Callable[[float], float], x: float, dx: float) -> float:
    """Simple central finite difference derivative."""
    return (f(x + dx) - f(x - dx)) / (2.0 * dx)


def load_cavity_simulation_output(path: Optional[str | Path] = None, geometry: Optional[str] = None) -> dict:
    """Load cavity simulation JSON output generated by cavity_geometry.py.

    Default layout is:
      results/<geometry>/cavity_simulation_output.json
    """
    if path is None:
        results_root = Path(__file__).resolve().parents[1] / "results"
        if geometry is not None:
            path = results_root / geometry / "cavity_simulation_output.json"
        else:
            # Prefer the newest geometry-specific result.
            candidates = list(results_root.glob("*/cavity_simulation_output.json"))
            if candidates:
                path = max(candidates, key=lambda p: p.stat().st_mtime)
            else:
                raise FileNotFoundError(
                    f"No cavity simulation output found under: {results_root}"
                )
    else:
        path = Path(path)

    if not path.exists():
        raise FileNotFoundError(f"Cavity simulation output not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


@dataclass(frozen=True)
class CrystalContext:
    """Minimal cavity-derived inputs needed by later crystal/OPO layers."""

    geometry: Optional[str]
    crystal_length_m: Optional[float]
    waist_crystal_m: Optional[float]
    waist_location_m: Optional[float]
    fsr_hz: Optional[float]
    kappa_ext_rad_s: Optional[float]
    kappa_loss_rad_s: Optional[float]
    kappa_rad_s: Optional[float]
    eta_escape: Optional[float]
    detuning_rad_s: Optional[float]
    raw: dict[str, Any]


@dataclass(frozen=True)
class PhaseMatchingResult:
    """Structured output for phase-matching / QPM calculations."""

    T_K: float
    n_p: float
    n_s: float
    n_i: float
    delta_k_rad_per_m: float
    delta_k_eff_rad_per_m: float
    pm_power: float
    Lambda_T_m: float


def build_crystal_context_from_cavity_output(cavity_data: dict) -> CrystalContext:
    """Extract the main geometry outputs needed by thermal / nonlinear layers.

    The JSON schema may evolve, so this function is intentionally tolerant and
    tries a few common key names before falling back to ``None``.
    """

    def pick(d: dict, *keys: str):
        for key in keys:
            if key in d:
                return d[key]
        return None

    geometry = pick(cavity_data, "geometry", "GEOMETRY")
    crystal_length_m = pick(cavity_data, "crystal_length_m", "f_crystal_length")
    waist_crystal_m = pick(cavity_data, "w0_crystal_m", "waist_crystal_m", "w0_m")
    waist_location_m = pick(cavity_data, "waist_location_m", "waist_position_m", "waist_s_m")
    fsr_hz = pick(cavity_data, "fsr_hz", "FSR_Hz", "fsr")
    kappa_ext_rad_s = pick(cavity_data, "kappa_ext_rad_s", "kappa_ext")
    kappa_loss_rad_s = pick(cavity_data, "kappa_loss_rad_s", "kappa_loss")
    kappa_rad_s = pick(cavity_data, "kappa_rad_s", "kappa")
    eta_escape = pick(cavity_data, "eta_escape", "escape_efficiency")
    detuning_rad_s = pick(cavity_data, "detuning_rad_s", "Delta_rad_s", "detuning")

    return CrystalContext(
        geometry=geometry,
        crystal_length_m=None if crystal_length_m is None else float(crystal_length_m),
        waist_crystal_m=None if waist_crystal_m is None else float(waist_crystal_m),
        waist_location_m=None if waist_location_m is None else float(waist_location_m),
        fsr_hz=None if fsr_hz is None else float(fsr_hz),
        kappa_ext_rad_s=None if kappa_ext_rad_s is None else float(kappa_ext_rad_s),
        kappa_loss_rad_s=None if kappa_loss_rad_s is None else float(kappa_loss_rad_s),
        kappa_rad_s=None if kappa_rad_s is None else float(kappa_rad_s),
        eta_escape=None if eta_escape is None else float(eta_escape),
        detuning_rad_s=None if detuning_rad_s is None else float(detuning_rad_s),
        raw=cavity_data,
    )


# %%
# -----------------------------
# Sellmeier / refractive index
# -----------------------------

@dataclass(frozen=True)
class SellmeierCoefficients:
    """Generic Sellmeier-like model container.

    This is intentionally generic: different crystals/polarizations use different
    functional forms and coefficient sets.

    The default evaluator implemented below uses the common form:

        n^2(λ) = A + B/(λ^2 - C) + D/(λ^2 - E) + F*λ^2

    with λ in micrometers.

    If you want a different model, provide your own evaluator function.
    """

    A: float
    B: float
    C: float
    D: float = 0.0
    E: float = 0.0
    F: float = 0.0


def n_sellmeier_um(lambda_um: np.ndarray | float, coeffs: SellmeierCoefficients) -> np.ndarray | float:
    """Compute refractive index from a common Sellmeier form.

    Parameters
    ----------
    lambda_um:
        Wavelength in micrometers.
    coeffs:
        Sellmeier coefficients.

    Returns
    -------
    n:
        Refractive index (dimensionless).
    """
    lam2 = np.asarray(lambda_um, dtype=float) ** 2
    n2 = (
        coeffs.A
        + coeffs.B / (lam2 - coeffs.C)
        + (coeffs.D / (lam2 - coeffs.E) if coeffs.D != 0.0 else 0.0)
        + coeffs.F * lam2
    )
    n = np.sqrt(n2)
    return n if isinstance(lambda_um, np.ndarray) else float(n)


def n_from_model(
    wavelength_m: np.ndarray | float,
    T_K: float,
    n_lambda: Callable[[np.ndarray | float], np.ndarray | float],
    dn_dT_perK: Optional[Callable[[float], float]] = None,
    T_ref_K: float = 293.15,
) -> np.ndarray | float:
    """Generic thermo-optic wrapper: n(λ, T) = n(λ) + (dn/dT)*(T - T_ref).

    Many crystals use more elaborate temperature models; this is a useful baseline.

    Parameters
    ----------
    wavelength_m:
        Wavelength in meters.
    T_K:
        Temperature in Kelvin.
    n_lambda:
        Function that returns n(λ) at reference temperature.
    dn_dT_perK:
        Optional function returning dn/dT [1/K]. If None, assumes 0.
    T_ref_K:
        Reference temperature for n_lambda.

    Returns
    -------
    n:
        Refractive index at (λ, T).
    """
    n0 = n_lambda(wavelength_m)
    if dn_dT_perK is None:
        return n0

    wl = np.asarray(wavelength_m, dtype=float)
    if wl.ndim == 0:
        dn = dn_dT_perK(float(wl))
        return n0 + dn * (T_K - T_ref_K)

    dn_vec = np.vectorize(lambda w: dn_dT_perK(float(w)), otypes=[float])(wl)
    return np.asarray(n0, dtype=float) + dn_vec * (T_K - T_ref_K)


def dn_dT_numeric(
    n_of_T: Callable[[float], float],
    T_K: float,
    dT_K: float = 1e-2,
) -> float:
    """Numerical derivative dn/dT at a given temperature."""
    return central_diff(n_of_T, T_K, dT_K)


# %%
# -----------------------------
# Wave-vectors and phase-matching
# -----------------------------

def k_of_n(wavelength_m: np.ndarray | float, n: np.ndarray | float) -> np.ndarray | float:
    """Wave-vector magnitude k = 2π n / λ (rad/m)."""
    wl = np.asarray(wavelength_m, dtype=float)
    nn = np.asarray(n, dtype=float)
    k = 2.0 * np.pi * nn / wl
    return k if isinstance(wavelength_m, np.ndarray) or isinstance(n, np.ndarray) else float(k)


def delta_k_three_wave(
    wavelength_p_m: float,
    wavelength_s_m: float,
    wavelength_i_m: float,
    n_p: float,
    n_s: float,
    n_i: float,
) -> float:
    """Compute phase-mismatch Δk = k_p - k_s - k_i (rad/m)."""
    k_p = k_of_n(wavelength_p_m, n_p)
    k_s = k_of_n(wavelength_s_m, n_s)
    k_i = k_of_n(wavelength_i_m, n_i)
    return float(k_p - k_s - k_i)


def qpm_grating_k(Lambda_m: float) -> float:
    """QPM grating wave-vector: K_g = 2π/Λ (rad/m)."""
    return float(2.0 * np.pi / Lambda_m)


def delta_k_qpm(
    delta_k_rad_per_m: float,
    Lambda_m: float,
    m: int = 1,
) -> float:
    """QPM-adjusted mismatch: Δk_eff = Δk - m*(2π/Λ)."""
    return float(delta_k_rad_per_m - m * qpm_grating_k(Lambda_m))


def pm_amplitude_factor(delta_k_eff: float, L_crystal_m: float) -> float:
    """Amplitude phase-matching factor for a uniform crystal: sinc(Δk L/2)."""
    return float(sinc(0.5 * delta_k_eff * L_crystal_m))


def pm_power_factor(delta_k_eff: float, L_crystal_m: float) -> float:
    """Power/efficiency factor ~ |sinc(Δk L/2)|^2."""
    a = pm_amplitude_factor(delta_k_eff, L_crystal_m)
    return float(a * a)


# %%
# -----------------------------
# Thermal expansion (poling period, lengths)
# -----------------------------

def expand_linear(L0: float, T_K: float, T0_K: float, alpha_perK: float) -> float:
    """Linear expansion: L(T) = L0 * (1 + α (T - T0))."""
    return float(L0 * (1.0 + alpha_perK * (T_K - T0_K)))


def poling_period_T(
    Lambda0_m: float,
    T_K: float,
    T0_K: float = 293.15,
    alpha_perK: float = 0.0,
) -> float:
    """Temperature-adjusted poling period Λ(T) via linear expansion.

    This is a baseline model. Some crystals use higher-order polynomials.
    """
    return expand_linear(Lambda0_m, T_K, T0_K, alpha_perK)


# %%
# -----------------------------
# Convenience: compute Δk_eff(T) from callbacks
# -----------------------------

def delta_k_eff_T(
    T_K: float,
    wavelength_p_m: float,
    wavelength_s_m: float,
    wavelength_i_m: float,
    n_p_of_T: Callable[[float], float],
    n_s_of_T: Callable[[float], float],
    n_i_of_T: Callable[[float], float],
    Lambda0_m: float,
    L_crystal_m: float,
    T0_K: float = 293.15,
    alpha_perK: float = 0.0,
    qpm_order_m: int = 1,
) -> PhaseMatchingResult:
    """Compute phase-matching / QPM quantities at temperature ``T_K``.

    Returns a structured ``PhaseMatchingResult`` instead of a raw tuple.
    """
    n_p = float(n_p_of_T(T_K))
    n_s = float(n_s_of_T(T_K))
    n_i = float(n_i_of_T(T_K))

    dk = delta_k_three_wave(wavelength_p_m, wavelength_s_m, wavelength_i_m, n_p, n_s, n_i)
    Lambda_T = poling_period_T(Lambda0_m, T_K, T0_K=T0_K, alpha_perK=alpha_perK)
    dk_eff = delta_k_qpm(dk, Lambda_T, m=qpm_order_m)
    pm_pow = pm_power_factor(dk_eff, L_crystal_m)

    return PhaseMatchingResult(
        T_K=float(T_K),
        n_p=n_p,
        n_s=n_s,
        n_i=n_i,
        delta_k_rad_per_m=float(dk),
        delta_k_eff_rad_per_m=float(dk_eff),
        pm_power=float(pm_pow),
        Lambda_T_m=float(Lambda_T),
    )


def scan_phase_matching_vs_temperature(
    T_min_K: float,
    T_max_K: float,
    n_T: int,
    wavelength_p_m: float,
    wavelength_s_m: float,
    wavelength_i_m: float,
    n_p_of_T: Callable[[float], float],
    n_s_of_T: Callable[[float], float],
    n_i_of_T: Callable[[float], float],
    Lambda0_m: float,
    L_crystal_m: float,
    T0_K: float = 293.15,
    alpha_perK: float = 0.0,
    qpm_order_m: int = 1,
) -> dict[str, np.ndarray]:
    """Scan phase-matching quantities versus temperature.

    Returns arrays that are convenient for plotting or for selecting the optimal
    operating temperature for the next simulation layer.
    """
    Ts = np.linspace(float(T_min_K), float(T_max_K), int(n_T))

    n_p_vals = np.empty_like(Ts)
    n_s_vals = np.empty_like(Ts)
    n_i_vals = np.empty_like(Ts)
    dk_vals = np.empty_like(Ts)
    dk_eff_vals = np.empty_like(Ts)
    pm_vals = np.empty_like(Ts)
    Lambda_vals = np.empty_like(Ts)

    for i, T in enumerate(Ts):
        res = delta_k_eff_T(
            T,
            wavelength_p_m,
            wavelength_s_m,
            wavelength_i_m,
            n_p_of_T,
            n_s_of_T,
            n_i_of_T,
            Lambda0_m,
            L_crystal_m,
            T0_K=T0_K,
            alpha_perK=alpha_perK,
            qpm_order_m=qpm_order_m,
        )
        n_p_vals[i] = res.n_p
        n_s_vals[i] = res.n_s
        n_i_vals[i] = res.n_i
        dk_vals[i] = res.delta_k_rad_per_m
        dk_eff_vals[i] = res.delta_k_eff_rad_per_m
        pm_vals[i] = res.pm_power
        Lambda_vals[i] = res.Lambda_T_m

    i_best = int(np.argmax(pm_vals))

    return {
        "T_K": Ts,
        "n_p": n_p_vals,
        "n_s": n_s_vals,
        "n_i": n_i_vals,
        "delta_k_rad_per_m": dk_vals,
        "delta_k_eff_rad_per_m": dk_eff_vals,
        "pm_power": pm_vals,
        "Lambda_T_m": Lambda_vals,
        "T_best_K": np.array([Ts[i_best]]),
        "pm_power_best": np.array([pm_vals[i_best]]),
    }


# %%
if __name__ == "__main__":
    # Minimal smoke-test: check that helpers run.
    # Replace the below with real coefficient sets/callbacks in your main code.

    # Example: constant n(T) callbacks
    n_p_of_T = lambda T: 1.8
    n_s_of_T = lambda T: 1.75
    n_i_of_T = lambda T: 1.75

    T = 300.0
    wl_p = 775e-9
    wl_s = 1550e-9
    wl_i = 1550e-9

    res = delta_k_eff_T(
        T,
        wl_p,
        wl_s,
        wl_i,
        n_p_of_T,
        n_s_of_T,
        n_i_of_T,
        Lambda0_m=9.0e-6,
        L_crystal_m=10e-3,
        alpha_perK=0.0,
    )

    print("Δk       =", res.delta_k_rad_per_m, "rad/m")
    print("Δk_eff   =", res.delta_k_eff_rad_per_m, "rad/m")
    print("PM power =", res.pm_power)
# %%
